name: 游 Bugrapport
description: Registrer en feil eller uventet oppf칮rsel
title: "[Bug]: <tittel> "
type: 'Bug'
labels:
    - bug
    - needs-triage
body:
  - type: textarea
    attributes:
      label: Beskrivelse av hendelsen
      description: Gi en klar og detaljert beskrivelse av hva som skjedde.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Hvordan reprodusere
      description: | 
        Oppgi s친 mye som mulig for 친 reprodusere feilen, dette kan inkludere:
        * et eksempelprosjekt (zip-fil) som p친viser feilen,
        * et kodeeksempel,
        * trinn-for-trinn instruksjoner for 친 reprodusere feilen.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Forventet oppf칮rsel
      description: Forventet resultat eller oppf칮rsel.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Faktisk oppf칮rsel
      description: Faktisk resultat eller oppf칮rsel.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Analyse av problemet
      description: Hvis du har tanker om hvor problemet oppst친r, beskriv det her. Inkluder referanser til kode, relevante endringer eller relaterte problemer du kjenner til.
